another change

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,10 +1,9 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
-
-if npm test -- --ignore; then
-  exit 0
+cmd //C "npm test"
+if [ $? -eq 0 ]; then
+    echo "Tests passed."
+    exit 0
 else
-  echo "Tests must pass before push!"
-  exit 1
+    echo "Tests failed. Push aborted."
+    exit 1
 fi
-```
